insert into genre (parent_id, slug, name) values (null, 'cnq-lwo', 'Easy reading');
insert into genre (parent_id, slug, name) values (1, 'jzy-rtn', 'Fiction');
insert into genre (parent_id, slug, name) values (1, 'rkw-cvk', 'militants');
insert into genre (parent_id, slug, name) values (1, 'ezt-pxx', 'detectives');
insert into genre (parent_id, slug, name) values (4, 'hcr-ddd', 'Thriller');
insert into genre (parent_id, slug, name) values (4, 'ixb-oiz', 'Cool detective');
insert into genre (parent_id, slug, name) values (4, 'zoz-vbg', 'Ironic detective');
insert into genre (parent_id, slug, name) values (4, 'scz-uhw', 'About maniacs');
insert into genre (parent_id, slug, name) values (4, 'glq-zbh', 'Spy detective');
insert into genre (parent_id, slug, name) values (4, 'mpw-zyj', 'Crime detective');
insert into genre (parent_id, slug, name) values (4, 'yae-uaq', 'Classic detective');
insert into genre (parent_id, slug, name) values (4, 'ltr-fkl', 'political detective');
insert into genre (parent_id, slug, name) values (1, 'car-dlf', 'fantasy');
insert into genre (parent_id, slug, name) values (1, 'lrx-prz', 'Novels');
insert into genre (parent_id, slug, name) values (1, 'brr-mon', 'horror');
insert into genre (parent_id, slug, name) values (1, 'yil-iqn', 'Adventures');
insert into genre (parent_id, slug, name) values (null, 'bkx-clq', 'Serious Reading');
insert into genre (parent_id, slug, name) values (17, 'bzt-opr', 'Biographies');
insert into genre (parent_id, slug, name) values (null, 'gsk-pph', 'business literature');
insert into genre (parent_id, slug, name) values (19, 'syg-gsy', 'business literature');
insert into genre (parent_id, slug, name) values (19, 'ygp-upj', 'Economic management');
insert into genre (parent_id, slug, name) values (19, 'hhq-grf', 'Career');
insert into genre (parent_id, slug, name) values (19, 'shg-zws', 'Marketing, PR, advertising');
insert into genre (parent_id, slug, name) values (19, 'nyi-hia', 'Finance');
insert into genre (parent_id, slug, name) values (19, 'nxr-uuu', 'Business directories');
insert into genre (parent_id, slug, name) values (19, 'skn-pfn', 'personal finance');
insert into genre (parent_id, slug, name) values (19, 'dqv-byk', 'Management');
insert into genre (parent_id, slug, name) values (19, 'ldl-tss', 'Foreign business literature');
insert into genre (parent_id, slug, name) values (19, 'qup-bca', 'Personal efficiency');
insert into genre (parent_id, slug, name) values (19, 'hfq-kcq', 'Time management');
insert into genre (parent_id, slug, name) values (19, 'afb-ghg', 'Small business');
insert into genre (parent_id, slug, name) values (19, 'reb-dnn', 'Sales');
insert into genre (parent_id, slug, name) values (19, 'xkp-jey', 'Startups and business creation');
insert into genre (parent_id, slug, name) values (19, 'asq-war', 'Corporate culture');
insert into genre (parent_id, slug, name) values (19, 'joq-ymv', 'Banking');
insert into genre (parent_id, slug, name) values (19, 'ppt-zap', 'Logistics');
insert into genre (parent_id, slug, name) values (19, 'gqd-gur', 'Real estate');
insert into genre (parent_id, slug, name) values (19, 'kac-cnd', 'Internet business');
insert into genre (parent_id, slug, name) values (19, 'uyk-egy', 'Oratory / rhetoric');
insert into genre (parent_id, slug, name) values (19, 'zoe-xqg', 'Customer acquisition and loyalty');
insert into genre (parent_id, slug, name) values (19, 'xfz-rwd', 'office work');
insert into genre (parent_id, slug, name) values (19, 'skv-kgk', 'Negotiation');
insert into genre (parent_id, slug, name) values (19, 'tsb-sxs', 'State and municipal administration, political administration');
insert into genre (parent_id, slug, name) values (19, 'qrf-zxs', 'About business popular');
insert into genre (parent_id, slug, name) values (19, 'bqh-qng', 'Securities / investments');
insert into genre (parent_id, slug, name) values (19, 'htb-lnz', 'Accounting / taxation / audit');
insert into genre (parent_id, slug, name) values (19, 'fwr-gpm', 'Russian practice');
insert into genre (parent_id, slug, name) values (19, 'qkw-smj', 'Success stories');
insert into genre (parent_id, slug, name) values (19, 'hrs-etw', 'Internet Marketing');
insert into genre (parent_id, slug, name) values (19, 'ifm-lyv', 'Leadership');
insert into genre (parent_id, slug, name) values (19, 'ita-bei', 'Project management');
insert into genre (parent_id, slug, name) values (19, 'zyl-qjn', 'Quality control');
insert into genre (parent_id, slug, name) values (19, 'jsr-fjt', 'Financial management');
insert into genre (parent_id, slug, name) values (19, 'oix-gmv', 'Personnel Management');
insert into genre (parent_id, slug, name) values (19, 'dff-eur', 'Business processes');
insert into genre (parent_id, slug, name) values (19, 'doe-lxa', 'Business management');
insert into genre (parent_id, slug, name) values (null, 'joa-ucw', 'Dramaturgy');
insert into genre (parent_id, slug, name) values (57, 'zbm-jbr', 'antique drama');
insert into genre (parent_id, slug, name) values (57, 'all-oub', 'Comedy');
insert into genre (parent_id, slug, name) values (57, 'qjp-lrb', 'Scenario');
insert into genre (parent_id, slug, name) values (57, 'rlq-shn', 'Drama, play');